### ISSUE TITLE
`list_remove` possibly not removing node completely

### ISSUE THREAD

**Issue by 3vcloud** [reduf/Headquarter#12]
Compiling on Windows (can we get a label for this?)

Had a crash when subscribing/unsubscribing to an event via `events_add_entry` and `events_rem_entry` in `events.c`, see below

```c
void broadcast_event(EventManager *mgr, EventType e, void *args)
{
    assert(0 <= e && e < N_EVENT);
    CallbackEntry *entry;
    struct list   *it;
    list_for_each(&mgr->callbacks[e], it) {
        entry = list_entry(it, CallbackEntry, node);
        assert(entry); // This should never happen if `events_rem_entry` is working correctly?
        if (entry->callback) {
            entry->callback(e, args, entry->param);
        }
    }
}
```
I've added the assertion here to flag it up; in theory `entry` should never be a null pointer, is this correct? Otherwise we need 
```c
        if (entry && entry->callback) {
            entry->callback(e, args, entry->param);
        }
```

To catch it, but this feels wrong too.

**Comment by 3vcloud** [comment]
Problem was borked debug code
```c
void events_rem_entry(EventManager *mgr, CallbackEntry *entry)
{
    assert(mgr && entry);
    struct list *node = &entry->node;
    assert(node->next && node->prev);
    list_remove(node);
#if !defined(NDEBUG)
    node->next = NULL;
    node->prev = NULL;
#endif
    entry->registered = false;
}
```
Will leave this open until I've sorted a PR or its removed

**Comment by reduf** [comment]
I don't see issue with the presented code although the error you mentioned is definitely an error. Is it possible that the event handler was removed from within the even handler?

**Comment by 3vcloud** [comment]
Just came across same issue in `rbtree.c` with the debug code nullifying next/prev

**Comment by reduf** [comment]
I got the confirmation that the event was unregistered from within the event handler. It's one point for the debug code that made it a reliable crash instead of a undefined behavior!

Anyway, I will adapt the code to be able to remove a callback from within the handler.

What was the issue with `rbtree.c`?

**Comment by 3vcloud** [comment]
Theres another few lines of debug code that caused a similar crash related to nullifying a node

**Comment by reduf** [comment]
Well, as I said, those lines of debug code are correct. The issue was calling `UnregisterEvent` from within the same event handler, but I addressed this problem to allow it to work. You can check this commit 0efd303dee88ef31dc4bbe76b041f54fa72547dd.

Were was the crash caused will be the interesting question, because there is likely an incorrect usage of rbtree.
