### ISSUE TITLE
CMakeLists for client should use `CMAKE_CURRENT_SOURCE_DIR`

### ISSUE THREAD

**Issue by 3vcloud** [reduf/Headquarter#14]
When compiling a plugin with client as a dependency, `CMAKE_SOURCE_DIR` isn't the client source dir - use `CMAKE_CURRENT_SOURCE_DIR` as per common and portal CMakeLists files

**Comment by reduf** [comment]
This generally raise a question about how we want to do it. The design currently somewhat means that the plugins should be compiled as part of the project rather than compiling a plugin with `Headquarter` as a dependency.

This is similar to how LLVM & Clang does it, but maybe not the best. Did you have a look at how the `chat` plugin was compiled?
